%% %odor list
odor_list = [{'water'}; ...             
    {'1-pentanol'}; ...        %alcohol 
    {'3-pentanol'}; ...
    {'trans-3-hexen-1-ol'}; ...
    {'6-methyl-5-hepten-2-ol' }; ...
    {'3-octanol'}; ...                  
    {'methyl phenyl sulfide'}; ...      %phenyl group
    {'anisole'}; ...
    {'2-acetylpyridine'}; ...
    {'2,5-dimethylpyrazine'}; ...   
    {'pentyl acetate'}; ...             %acetate
    {'geranyl acetate'}; ...
    {'2-methoxyphenyl acetate'}; ...
    {'trans-2-hexen-1-al'}; ...         %aldehyde
    {'trans,trans-2,4-nonadienal'}; ...
    {'4-methyl-5-vinylthiazole'}; ...   %thiazole
    {'4,5-dimethylthiazole'}; ...
    {'4-hexen-3-one'}; ...              %ketone
    {'2-nonanone'}; ...                 
    {'acetal'}; ...                     %acetal
    {'2-phenylethanol'}; ...            %alcohol and aromatic
    {'ethyl hexanote'}; ...             %ethyl hexanote
    {'linalool'};...                    %strawberry odors
    {'methyl hexanoate'};...
    {'2-butoxy ethanol'};...
    {'hexyl acetate'};...
    {'methyl salicylate'};...
    {'benzyl acetate'};...
    {'butyl acetate'};...
    {'isopropyl butyrate'};...
    {'isopentyl acetate'};...
    {'methyl isovalerate'};...
    {'methyl butyrate'};... 
    {'2-heptanone'}; ...                   %aromatic
     {'fluorescein'}; ...
        {'L-glutamic acid'}; ...
        {'L-argenine'}; ...
        {'fructose'}; ...    
        {'citric acid'}; ...
        {'caffeine'}; ...             %gustatory tastants
        {'NaCL'}; ... 
        {'denatonium benzoate'}; ...                    
        {'KCL'}; ...             
        {'sucrose'}; ... 
        {'arabinose'}; ... 
        {'ethyl acetate & 200mM fructose'};...
        {'diacetyl'};...
        {'benzaldchydc'};...
        {'isoamyl alcohol'};...
        {'1-pentanol & 3-pentanol'};...
        {'ethyl acetate'};...
        {'diacetyl'};...
        {'NMM'};...
        {'1mM NMM & 1-pentanol'};...
        {'4,5-dimethylthiazole & 2-phenyl ethanol'};...
        {'3-pentanol & 2-phenyl ethanol'};...
        {'acetal & 3-pentanol'};...
        {'acetal & 1-pentanol'};...
        {'1-pentanol & 4,5-dimethylthiazole'};...
        {'acetal & 4,5-dimethylthiazole'};...
        {'acetal & 3-pentanol'};...
        {'acetal & 2-phenyl ethanol'};...
        {'4,5-dimethylthiazole & 3-pentanol'};...
        {'1-pentanol & 2-phenyl ethanol'};...
        {'3-pentanol & 4-hexen-3-one'};...
        {'anisole & 4-hexen-3-one'};...
        {'NaHCO3'};...
        {'ScramMaleP'};...
        {'MaleP'};...
        {'1-octanol'};...
        {'4-methyl-5-vinylthiazole & 3-octanol'};...
        {'4-methyl-5-vinylthiazole & methyl phenyl sulphide & pentyl acetate'};...
        {'4-methyl-5-vinylthiazole & pentyl acetate'};...
        {'pentyl acetate & methyl phenyl sulfide'};...
        {'pentyl acetate & methyl phenyl sulfide & 3-octanol'};...
        {'pentyl acetate & 4-methyl-5-vinylthiazole & 3-octanol'};...
        {'4-methyl-5-vinylthiazole & 3-octanol'};...
        {'pentyl acetate & 3-octanol'};...
        {'4-methyl-5-vinylthiazole & 3-octanol & methyl phenyl sulfide'};...
        {'pentyl acetate & 4-methyl-5-vinylthiazole & 3-octanol & methyl phenyl sulfide'};...
        {'6-methyl-5-hepten-2-ol & 3-pentanol'};...
        {'6-methyl-5-hepten-2-ol & 4-methyl-5-vinylthiazole'};...
        {'6-methyl-5-hepten-2-ol & methyl phenyl sulphide'};...
        {'3-pentanol & methyl phenyl sulphide'};...
        {'3-pentanol & 4-methyl-5-vinylthiazole'};...
        {'6-methyl-5-hepten-2-ol & 3-pentanol & 4-methyl-5-vinylthiazole'};...
        {'6-methyl-5-hepten-2-ol & 3-pentanol & methyl phenyl sulphide'};...
        {'6-methyl-5-hepten-2-ol & 3-pentanol & 4-methyl-5-vinylthiazole & methyl phenyl sulphide'};...
        {'1-nonanol'};...
        {'1-hexanol'};...
        {'1-heptanol'};];
                 
%% %concentration list
odor_concentration_list = [{'10^-8'}; {'10^-7'}; {'10^-6'}; {'10^-5'}; {'10^-4'};{'10^-3'}; ...
    {'3x10^-6'}; {'3x10^-5'}; {'3x10^-4'} ;...
    {'200uM'};{'500uM'}; {'1mM'}; {'2mM'}; {'5mM'}; {'10mM'}; {'20mM'};  {'50mM'}; {'100mM'}; {'200mM'};  {'500mM'}; {'1M'}; {'2M'};...
    {'3x10^-6;10^-7'}; {'3x10^-6;10^-6'}; {'3x10^-6;10^-5'};{'3x10^-6;10^-4'}; ...
    {'10^-5;10^-7'}; {'10^-5;10^-6'}; {'10^-5;10^-5'};{'10^-5s;10^-4'}; ...
    {'10^-7;10^-6'};{'10^-6;10^-6'};{'10^-5;10^-6'};{'10^-6;10^-5'};{'10^-5;10^-5'};{'10^-5;5x10^-6'};{'10^-5;10^-7'};{'10^-5;3x10^-7'};...
    {'10^-5;3x10^-6'};{'10^-4;10^-6'};{'10^-6;10^-4'};{'10^-4.3'};{'10^-4.7'};...
    {'2x10^-5'};{'5x10^-5'};{'2x10^-6'};{'5x10^-6'};{'2x10^-7'};{'5x10^-7'};{'7.5x10^-5'};{'2.5x10^-5'}; ...
    {'10^-6;10^-6;10^-6'}; {'10^-6;10^-6;10^-6;10^-6'}; {'5x10^-7;10^-6;10^-6'};  {'5x10^-7;10^-6'};{'5x10^-7;10^-6;10^-6;10^-6'};...
    {'1x'};{'.9x'};{'.8x'};{'.7x'};{'.5x'};{'.3x'};{'.2x'};{'.1x'};{'.05x'}];    %concentrations
    
%odor_concentration_list = [{'10^-8'}; {'10^-7'}; {'10^-6'}; {'10^-5'}; {'10^-4'}; {'1 mM'}; {'2 mM'}; {'5 mM'};  {'6 mM'}; {'10 mM'}; {'20 mM'}; {'50 mM'}; {'100 mM'}; {'200 mM'};  {'500 mM'}; {'1 M'}; {'2 M'}];    %concentrations

%% %colormap
odor_num = length(odor_list);
con_num = length(odor_concentration_list);

color_num = odor_num*con_num;
if color_num<128
    color_num = 128;
elseif color_num<256
    color_num = 256;
elseif color_num<512
    color_num = 512;
end

odor_colormap = colorcube(color_num); 
odor_colormap = odor_colormap(1:odor_num*con_num,:); 

%% %show colormap
data_show = 1:odor_num*con_num;
data_show = reshape(data_show,con_num, odor_num)';

figure
imagesc(data_show); 
colormap(odor_colormap);

title('Odor Colormap')
set(gca,'XTick',1:con_num);
set(gca,'XTickLabel',odor_concentration_list)
xlabel('Concentration');
set(gca,'YTick',1:odor_num);
set(gca,'YTickLabel',odor_list);
ylabel('Odor Type');

%% Save data and figure
currentFolder = pwd;
path = [currentFolder, '\data\'];
if ~exist(path, 'dir');
    mkdir(path);
end
save([path, 'odor_inf'], 'odor_list', 'odor_concentration_list', 'odor_colormap');
saveas(gcf,[path, 'odor_colormap.fig']);